site_name: TT425 Manual
site_description: TT425 Manual
site_url: https://hm-info.github.io/tt425/

docs_dir: docs

theme:
  name: material
  language: tr
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: blue-grey
      accent: blue-grey

nav:
  - Ana Sayfa / Home: index.md
  - 🇹🇷 Türkçe: Turkish.md
  - 🇬🇧 English: English.md

use_directory_urls: false

plugins:
  - search
